/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.org.sparks_of_fabrication.imgstenography.graphics.textpanels;

import com.github.org.sparks_of_fabrication.imgstenography.graphics.ChildPanel;
import com.github.org.sparks_of_fabrication.imgstenography.loaders.TextFileLoader;

/**
 *
 * @author petko
 */
public class TextInputPanelSwitcher extends javax.swing.JPanel implements ChildPanel<TextFileLoader> {
    private boolean mode = false;
   
    private void toggle() {
        textInputFilePanel1.setVisible(mode);
        textInputPanel1.setVisible(!mode);
        
        mode = !mode;
    }
    /**
     * Creates new form TextInputPanelSwitcher
     */
    public TextInputPanelSwitcher() {
        initComponents();
        toggle();
    }

    @Override
    public void inherit(TextFileLoader obj) {
        textInputFilePanel1.inherit(obj);
    }
    
    public void switchMode() {
        toggle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textInputPanel1 = new com.github.org.sparks_of_fabrication.imgstenography.graphics.textpanels.TextInputPanel();
        textInputFilePanel1 = new com.github.org.sparks_of_fabrication.imgstenography.graphics.textpanels.TextInputFilePanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(textInputFilePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(textInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(textInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textInputFilePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.org.sparks_of_fabrication.imgstenography.graphics.textpanels.TextInputFilePanel textInputFilePanel1;
    private com.github.org.sparks_of_fabrication.imgstenography.graphics.textpanels.TextInputPanel textInputPanel1;
    // End of variables declaration//GEN-END:variables
}
